//
// Copyright 2026 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/extGpuBufferSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
#include "pxr/imaging/hd/types.h"
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdExtGpuBufferSchemaTokens,
    HD_EXT_GPU_BUFFER_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--

bool
HdExtGpuBufferSchema::IsComplete() const
{
    const HdTokenDataSourceHandle api = GetBackendApi();
    const HdUInt64DataSourceHandle handle = GetRawHandle();
    const HdSizetDataSourceHandle count = GetNumElements();
    const HdTupleTypeDataSourceHandle elementType = GetElementType();

    if (!api || !handle || !count || !elementType) {
        return false;
    }
    if (handle->GetTypedValue(0.0f) == 0) {
        return false;
    }
    if (count->GetTypedValue(0.0f) == 0) {
        return false;
    }
    if (elementType->GetTypedValue(0.0f).type == HdTypeInvalid) {
        return false;
    }
    return true;
}

// --(END CUSTOM CODE: Schema Methods)--

HdTokenDataSourceHandle
HdExtGpuBufferSchema::GetBackendApi() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdExtGpuBufferSchemaTokens->backendApi);
}

HdUInt64DataSourceHandle
HdExtGpuBufferSchema::GetRawHandle() const
{
    return _GetTypedDataSource<HdUInt64DataSource>(
        HdExtGpuBufferSchemaTokens->rawHandle);
}

HdSizetDataSourceHandle
HdExtGpuBufferSchema::GetRawHandleByteSize() const
{
    return _GetTypedDataSource<HdSizetDataSource>(
        HdExtGpuBufferSchemaTokens->rawHandleByteSize);
}

HdSizetDataSourceHandle
HdExtGpuBufferSchema::GetNumElements() const
{
    return _GetTypedDataSource<HdSizetDataSource>(
        HdExtGpuBufferSchemaTokens->numElements);
}

HdTupleTypeDataSourceHandle
HdExtGpuBufferSchema::GetElementType() const
{
    return _GetTypedDataSource<HdTupleTypeDataSource>(
        HdExtGpuBufferSchemaTokens->elementType);
}

HdSizetDataSourceHandle
HdExtGpuBufferSchema::GetByteOffset() const
{
    return _GetTypedDataSource<HdSizetDataSource>(
        HdExtGpuBufferSchemaTokens->byteOffset);
}

HdSizetDataSourceHandle
HdExtGpuBufferSchema::GetByteStride() const
{
    return _GetTypedDataSource<HdSizetDataSource>(
        HdExtGpuBufferSchemaTokens->byteStride);
}

HdBoolDataSourceHandle
HdExtGpuBufferSchema::GetDirectBindable() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        HdExtGpuBufferSchemaTokens->directBindable);
}

/*static*/
HdContainerDataSourceHandle
HdExtGpuBufferSchema::BuildRetained(
        const HdTokenDataSourceHandle &backendApi,
        const HdUInt64DataSourceHandle &rawHandle,
        const HdSizetDataSourceHandle &rawHandleByteSize,
        const HdSizetDataSourceHandle &numElements,
        const HdTupleTypeDataSourceHandle &elementType,
        const HdSizetDataSourceHandle &byteOffset,
        const HdSizetDataSourceHandle &byteStride,
        const HdBoolDataSourceHandle &directBindable
)
{
    TfToken _names[8];
    HdDataSourceBaseHandle _values[8];

    size_t _count = 0;

    if (backendApi) {
        _names[_count] = HdExtGpuBufferSchemaTokens->backendApi;
        _values[_count++] = backendApi;
    }

    if (rawHandle) {
        _names[_count] = HdExtGpuBufferSchemaTokens->rawHandle;
        _values[_count++] = rawHandle;
    }

    if (rawHandleByteSize) {
        _names[_count] = HdExtGpuBufferSchemaTokens->rawHandleByteSize;
        _values[_count++] = rawHandleByteSize;
    }

    if (numElements) {
        _names[_count] = HdExtGpuBufferSchemaTokens->numElements;
        _values[_count++] = numElements;
    }

    if (elementType) {
        _names[_count] = HdExtGpuBufferSchemaTokens->elementType;
        _values[_count++] = elementType;
    }

    if (byteOffset) {
        _names[_count] = HdExtGpuBufferSchemaTokens->byteOffset;
        _values[_count++] = byteOffset;
    }

    if (byteStride) {
        _names[_count] = HdExtGpuBufferSchemaTokens->byteStride;
        _values[_count++] = byteStride;
    }

    if (directBindable) {
        _names[_count] = HdExtGpuBufferSchemaTokens->directBindable;
        _values[_count++] = directBindable;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdExtGpuBufferSchema::Builder &
HdExtGpuBufferSchema::Builder::SetBackendApi(
    const HdTokenDataSourceHandle &backendApi)
{
    _backendApi = backendApi;
    return *this;
}

HdExtGpuBufferSchema::Builder &
HdExtGpuBufferSchema::Builder::SetRawHandle(
    const HdUInt64DataSourceHandle &rawHandle)
{
    _rawHandle = rawHandle;
    return *this;
}

HdExtGpuBufferSchema::Builder &
HdExtGpuBufferSchema::Builder::SetRawHandleByteSize(
    const HdSizetDataSourceHandle &rawHandleByteSize)
{
    _rawHandleByteSize = rawHandleByteSize;
    return *this;
}

HdExtGpuBufferSchema::Builder &
HdExtGpuBufferSchema::Builder::SetNumElements(
    const HdSizetDataSourceHandle &numElements)
{
    _numElements = numElements;
    return *this;
}

HdExtGpuBufferSchema::Builder &
HdExtGpuBufferSchema::Builder::SetElementType(
    const HdTupleTypeDataSourceHandle &elementType)
{
    _elementType = elementType;
    return *this;
}

HdExtGpuBufferSchema::Builder &
HdExtGpuBufferSchema::Builder::SetByteOffset(
    const HdSizetDataSourceHandle &byteOffset)
{
    _byteOffset = byteOffset;
    return *this;
}

HdExtGpuBufferSchema::Builder &
HdExtGpuBufferSchema::Builder::SetByteStride(
    const HdSizetDataSourceHandle &byteStride)
{
    _byteStride = byteStride;
    return *this;
}

HdExtGpuBufferSchema::Builder &
HdExtGpuBufferSchema::Builder::SetDirectBindable(
    const HdBoolDataSourceHandle &directBindable)
{
    _directBindable = directBindable;
    return *this;
}

HdContainerDataSourceHandle
HdExtGpuBufferSchema::Builder::Build()
{
    return HdExtGpuBufferSchema::BuildRetained(
        _backendApi,
        _rawHandle,
        _rawHandleByteSize,
        _numElements,
        _elementType,
        _byteOffset,
        _byteStride,
        _directBindable
    );
}

/*static*/
HdExtGpuBufferSchema
HdExtGpuBufferSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdExtGpuBufferSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdExtGpuBufferSchemaTokens->extGpuBuffer))
        : nullptr);
}

/*static*/
const TfToken &
HdExtGpuBufferSchema::GetSchemaToken()
{
    return HdExtGpuBufferSchemaTokens->extGpuBuffer;
}

/*static*/
const HdDataSourceLocator &
HdExtGpuBufferSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/*static*/
HdTokenDataSourceHandle
HdExtGpuBufferSchema::BuildBackendApiDataSource(
    const TfToken &backendApi)
{

    if (backendApi == HdExtGpuBufferSchemaTokens->GL) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(backendApi);
        return ds;
    }
    if (backendApi == HdExtGpuBufferSchemaTokens->Vulkan) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(backendApi);
        return ds;
    }
    if (backendApi == HdExtGpuBufferSchemaTokens->Metal) {
        static const HdRetainedTypedSampledDataSource<TfToken>::Handle ds =
            HdRetainedTypedSampledDataSource<TfToken>::New(backendApi);
        return ds;
    }
    // fallback for unknown token
    return HdRetainedTypedSampledDataSource<TfToken>::New(backendApi);
}

PXR_NAMESPACE_CLOSE_SCOPE
