//
// Copyright 2026 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#ifndef PXR_IMAGING_HD_EXT_GPU_BUFFER_SCHEMA_H
#define PXR_IMAGING_HD_EXT_GPU_BUFFER_SCHEMA_H

/// \file

#include "pxr/imaging/hd/api.h"

#include "pxr/imaging/hd/schema.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

// --(BEGIN CUSTOM CODE: Declares)--
// --(END CUSTOM CODE: Declares)--

#define HD_EXT_GPU_BUFFER_SCHEMA_TOKENS \
    (extGpuBuffer) \
    (backendApi) \
    (rawHandle) \
    (rawHandleByteSize) \
    (numElements) \
    (elementType) \
    (byteOffset) \
    (byteStride) \
    (directBindable) \
    (GL) \
    (Vulkan) \
    (Metal) \

TF_DECLARE_PUBLIC_TOKENS(HdExtGpuBufferSchemaTokens, HD_API,
    HD_EXT_GPU_BUFFER_SCHEMA_TOKENS);

//-----------------------------------------------------------------------------


/// \class HdExtGpuBufferSchema
///
/// Describes an externally-owned GPU buffer that a producer publishes on a primvar so a
/// renderer can consume it directly instead of the CPU staging round trip.
///
class HdExtGpuBufferSchema : public HdSchema
{
public:
    /// \name Schema retrieval
    /// @{

    HdExtGpuBufferSchema(HdContainerDataSourceHandle container)
      : HdSchema(container) {}

    /// Retrieves a container data source with the schema's default name token
    /// "extGpuBuffer" from the parent container and constructs a
    /// HdExtGpuBufferSchema instance.
    /// Because the requested container data source may not exist, the result
    /// should be checked with IsDefined() or a bool comparison before use.
    HD_API
    static HdExtGpuBufferSchema GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer);

    /// @}

// --(BEGIN CUSTOM CODE: Schema Methods)--

    /// Returns true iff the required members (backendApi, rawHandle,
    /// numElements, elementType) are present and non-degenerate.  Consumers
    /// gate on this before reading; a false result means "fall back to the
    /// CPU primvar path".  No flattened POD is exposed -- decoding into a
    /// renderer-private value is each consumer's own concern.
    HD_API
    bool IsComplete() const;

// --(END CUSTOM CODE: Schema Methods)--

    /// \name Member accessor
    /// @{

    /// Graphics API that owns the handle ("GL"/"Vulkan"/"Metal").  A consumer
    /// compares it to its active Hgi backend and falls back to CPU on mismatch.
    HD_API
    HdTokenDataSourceHandle GetBackendApi() const;

    /// The opaque native buffer handle (GLuint / VkBuffer / MTLBuffer) cast to
    /// uint64.  Interpreted per backendApi; the resource to bind/import.
    HD_API
    HdUInt64DataSourceHandle GetRawHandle() const;

    /// Total size of the underlying native buffer.  Optional (0 = unknown);
    /// when set, it is the authoritative size for bounds checks and byteSize.
    HD_API
    HdSizetDataSourceHandle GetRawHandleByteSize() const;

    /// Number of tuples (vertices / elements) in this stream.
    HD_API
    HdSizetDataSourceHandle GetNumElements() const;

    /// Element type + tuple count (e.g. Float/Vec3), stored as an HdTupleType.
    HD_API
    HdTupleTypeDataSourceHandle GetElementType() const;

    /// Byte offset to the first element within the native buffer.  Non-zero
    /// means this stream is a sub-allocation of a larger (pooled) buffer.
    HD_API
    HdSizetDataSourceHandle GetByteOffset() const;

    /// Bytes between consecutive elements.  0 or == elemSize means tightly
    /// packed (directly aliasable); otherwise interleaved (strided copy).
    HD_API
    HdSizetDataSourceHandle GetByteStride() const;

    /// True if the consumer may bind the buffer directly (zero-copy).
    HD_API
    HdBoolDataSourceHandle GetDirectBindable() const;

    /// @}

    /// \name Schema location
    /// @{

    /// Returns a token where the container representing this schema is found in
    /// a container by default.
    HD_API
    static const TfToken &GetSchemaToken();

    /// Returns an HdDataSourceLocator (relative to the prim-level data source)
    /// where the container representing this schema is found by default.
    HD_API
    static const HdDataSourceLocator &GetDefaultLocator();

    /// @}

    /// \name Schema construction
    /// @{

    /// \deprecated Use Builder instead.
    ///
    /// Builds a container data source which includes the provided child data
    /// sources. Parameters with nullptr values are excluded.
    HD_API
    static HdContainerDataSourceHandle
    BuildRetained(
        const HdTokenDataSourceHandle &backendApi,
        const HdUInt64DataSourceHandle &rawHandle,
        const HdSizetDataSourceHandle &rawHandleByteSize,
        const HdSizetDataSourceHandle &numElements,
        const HdTupleTypeDataSourceHandle &elementType,
        const HdSizetDataSourceHandle &byteOffset,
        const HdSizetDataSourceHandle &byteStride,
        const HdBoolDataSourceHandle &directBindable
    );

    /// \class HdExtGpuBufferSchema::Builder
    ///
    /// Utility class for setting sparse sets of child data source fields to be
    /// filled as arguments into BuildRetained.
    class Builder
    {
    public:
        HD_API
        Builder &SetBackendApi(
            const HdTokenDataSourceHandle &backendApi);
        HD_API
        Builder &SetRawHandle(
            const HdUInt64DataSourceHandle &rawHandle);
        HD_API
        Builder &SetRawHandleByteSize(
            const HdSizetDataSourceHandle &rawHandleByteSize);
        HD_API
        Builder &SetNumElements(
            const HdSizetDataSourceHandle &numElements);
        HD_API
        Builder &SetElementType(
            const HdTupleTypeDataSourceHandle &elementType);
        HD_API
        Builder &SetByteOffset(
            const HdSizetDataSourceHandle &byteOffset);
        HD_API
        Builder &SetByteStride(
            const HdSizetDataSourceHandle &byteStride);
        HD_API
        Builder &SetDirectBindable(
            const HdBoolDataSourceHandle &directBindable);

        /// Returns a container data source containing the members set thus far.
        HD_API
        HdContainerDataSourceHandle Build();

    private:
        HdTokenDataSourceHandle _backendApi;
        HdUInt64DataSourceHandle _rawHandle;
        HdSizetDataSourceHandle _rawHandleByteSize;
        HdSizetDataSourceHandle _numElements;
        HdTupleTypeDataSourceHandle _elementType;
        HdSizetDataSourceHandle _byteOffset;
        HdSizetDataSourceHandle _byteStride;
        HdBoolDataSourceHandle _directBindable;

    };

    /// Returns token data source for use as backendApi value.
    ///
    /// The following values will be stored statically and reused for future
    /// calls:
    /// - HdExtGpuBufferSchemaTokens->GL
    /// - HdExtGpuBufferSchemaTokens->Vulkan
    /// - HdExtGpuBufferSchemaTokens->Metal
    HD_API
    static HdTokenDataSourceHandle BuildBackendApiDataSource(
        const TfToken &backendApi);

    /// @}
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif
